apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: demo-test
  name: kafka
spec:
  endpoints:
  - interval: 30s
    port: prometheus
  selector:
    matchLabels:
      type: kafka