apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
        - name: kafka-monitor
          image: quay.io/samsung_cnct/kafka-monitor:0.1
          ports:
            - containerPort: 8778
