apiVersion: v2
name: confluent-monitoring
version: 0.0.1
description: A helm chart for fully monitoring kafka on k8s
type: application
dependencies:
  - name: telegraf-operator
    version: 1.3.10
    repository: https://helm.influxdata.com/
    condition: telegraf-operator.enabled